# Generated by Django 5.2.4 on 2025-07-17 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_author_note_content_note_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('analysis_time', models.DateTimeField(auto_now_add=True)),
                ('parsed_data', models.JSONField()),
                ('analysis_results', models.JSONField()),
                ('ats_score', models.FloatField()),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
