# Generated by Django 5.2.4 on 2025-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userregisterdata_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='education',
            field=models.JSONField(default=list),
        ),
    ]
