# Generated by Django 5.2.4 on 2025-07-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resumeanalysis_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='experience_level',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='total_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
