# Generated by Django 5.2.4 on 2025-07-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resumeanalysis_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='total_experience',
        ),
    ]
