# Generated by Django 5.2.4 on 2025-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_resumeanalysis_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='education',
            field=models.JSONField(),
        ),
    ]
