# Generated by Django 5.2.4 on 2025-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_resumeanalysis_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='education',
            field=models.JSONField(default=list),
        ),
    ]
