# Generated by Django 5.2.4 on 2025-07-27 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_experience_responsibility_resume_project_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeneratedResumeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_sets', to='api.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resume_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimalist', 'Minimalist')], max_length=20)),
                ('pdf_file', models.BinaryField()),
                ('pdf_filename', models.CharField(max_length=255)),
                ('pdf_size', models.PositiveIntegerField()),
                ('thumbnail_image', models.BinaryField()),
                ('thumbnail_filename', models.CharField(max_length=255)),
                ('thumbnail_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('resume_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.generatedresumeset')),
            ],
            options={
                'ordering': ['template_name'],
                'unique_together': {('resume_set', 'template_name')},
            },
        ),
    ]
