# Generated by Django 5.2.4 on 2025-07-27 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_resume_profile_pic_generatedresumeset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_ats_score', models.FloatField(blank=True, null=True)),
                ('current_ats_score', models.FloatField()),
                ('score_improvement', models.FloatField(default=0)),
                ('changes_made', models.JSONField(default=list)),
                ('improvements_noted', models.JSONField(default=list)),
                ('recommendations_implemented', models.JSONField(default=list)),
                ('pending_recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSScoreBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info_score', models.FloatField(default=0)),
                ('summary_score', models.FloatField(default=0)),
                ('skills_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(default=0)),
                ('projects_score', models.FloatField(default=0)),
                ('formatting_score', models.FloatField(default=0)),
                ('keywords_score', models.FloatField(default=0)),
                ('personal_info_feedback', models.TextField(blank=True)),
                ('summary_feedback', models.TextField(blank=True)),
                ('skills_feedback', models.TextField(blank=True)),
                ('experience_feedback', models.TextField(blank=True)),
                ('education_feedback', models.TextField(blank=True)),
                ('projects_feedback', models.TextField(blank=True)),
                ('formatting_feedback', models.TextField(blank=True)),
                ('keywords_feedback', models.TextField(blank=True)),
                ('total_score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'Excellent (90-100)'), ('A', 'Very Good (80-89)'), ('B', 'Good (70-79)'), ('C', 'Fair (60-69)'), ('D', 'Poor (Below 60)')], max_length=2)),
                ('top_improvement_areas', models.JSONField(default=list)),
                ('estimated_improvement_time', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_keywords_found', models.JSONField(default=list)),
                ('technical_keywords_missing', models.JSONField(default=list)),
                ('technical_match_score', models.FloatField(default=0)),
                ('soft_skills_found', models.JSONField(default=list)),
                ('soft_skills_missing', models.JSONField(default=list)),
                ('soft_skills_match_score', models.FloatField(default=0)),
                ('industry_keywords_found', models.JSONField(default=list)),
                ('industry_keywords_missing', models.JSONField(default=list)),
                ('industry_match_score', models.FloatField(default=0)),
                ('action_verbs_found', models.JSONField(default=list)),
                ('action_verbs_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('match_percentage', models.FloatField()),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('skill_gap_score', models.FloatField(default=0)),
                ('experience_relevance_score', models.FloatField(default=0)),
                ('experience_feedback', models.TextField(blank=True)),
                ('education_relevance_score', models.FloatField(default=0)),
                ('education_feedback', models.TextField(blank=True)),
                ('market_demand', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('growth_prospects', models.TextField(blank=True)),
                ('role_specific_tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_percentage'],
            },
        ),
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={'ordering': ['-analysis_time']},
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='detailed_role_analysis',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='keywords_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='optimization_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='processing_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='role_predictions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='similarity_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='analysis_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='parsed_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['user', '-analysis_time'], name='api_resumea_user_id_f73be8_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['ats_score'], name='api_resumea_ats_sco_1d2574_idx'),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='resume_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='api.resumeanalysis'),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atsscorebreakdown',
            name='resume_analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_breakdown_detail', to='api.resumeanalysis'),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='resume_analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_analysis_detail', to='api.resumeanalysis'),
        ),
        migrations.AddField(
            model_name='roleanalysisdetail',
            name='resume_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_analysis_details', to='api.resumeanalysis'),
        ),
        migrations.AlterUniqueTogether(
            name='roleanalysisdetail',
            unique_together={('resume_analysis', 'role_name')},
        ),
    ]
